# BOF [O1o1o0g15o_13o1o0]
# 思考エンジンのデフォルト値です。 CgfGoBan などの GUI はこのファイルを見ません

# Game - 対局１つ分に相当
[Game]

# Komi - コミ
Komi = 6.5

# BoardSize - 何路盤
BoardSize = 19

# MaxMoves - 最大手数
MaxMoves = 400

# BoardData - 盤面
#
# * '.' - 空点
# * 'x' - 黒石
# * 'o' - 白石
# * '+' - 壁
# * 半角空白は無視します
BoardData = '''
+++++++++++++++++++++
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+...................+
+++++++++++++++++++++
'''

# EOF [O1o1o0g15o_13o1o0]
